on:
  push:
    paths:
      - '.github/workflows/mkvtoolnix.yml'
  schedule:
    - cron: "0 18 */1 * *"

name: Mirror Sync
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TZ: Europe/Busingen
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login into Github && Mirror
        run: |
          wget -qO- https://api.github.com/repos/cli/cli/releases/latest | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | grep "linux_amd64.tar.gz" | wget -i -
          mkdir -p gh && tar -zxf gh_*.tar.gz -C gh/ --strip-components=1
          mv gh/bin/gh github && rm -rf gh*
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "bolucat"
          echo ${{ secrets.TOKEN }} > token.txt
          chmod +x github && ./github auth login -p https --hostname "github.com" --with-token < token.txt
          rm -rf token.txt && ./github auth status
          git clone --recurse-submodules --bare https://gitlab.com/mbunkus/mkvtoolnix.git
          cd mkvtoolnix.git
          git remote set-url origin "https://bolucat:${{ secrets.TOKEN }}@github.com/bolucat/MKVToolNix.git"
          git push --mirror "https://bolucat:${{ secrets.TOKEN }}@github.com/bolucat/MKVToolNix.git"
          cd .. && rm -rf mkvtoolnix.git
          
